services:
  loop:
    build: .
    command: bash -c "apt-get update -y && apt-get install -y curl && while true; do curl https://github-readme-stats-dps0340.vercel.app/api?username=DPS0340&hide=contribs&count_private=true&show_icons=true&theme=radical&include_all_commits=true&custom_title=DPS0340\'s%20Github%20Stats; sleep 5s; done"
